### ISSUE TITLE
macro.execute wrapper does not seem to return the macro.execute promise

### ISSUE THREAD

**Issue by tposney** [MiahNelah/lib-blockly#41] opened 2023-11-02 13:10 UTC
I was having a play - great work by the way.

I noticed that with libBlockly installed modules that await macro.execute are not blocking, this came to my notice when testing chris's premade items. It seems to be the line
```js
  libBlockly._handleMacroExecution(this, wrapped, ...args);
```
if I change that to
```js
  return libBlockly._handleMacroExecution(this, wrapped, ...args);
```
things work as expected.

**Comment by MiahNelah** [comment] 2023-11-02 13:35
Hi @tposney ! Thanks for your feedback. I didn’t had time to work on this module since some time now, I need to look at it this evening. It sounds like a dumb issue, I’ll release a fix asap.

**Comment by MiahNelah** [comment] 2023-11-02 19:14
Have you an example to reproduce ? I tried with a lot of items, spells, features, ... A lot of them do not work, but I found none broken due to awaiting async macro.

**Comment by chrisk123999** [comment] 2023-11-02 20:16
It very much breaks things from my module Chris's Premades.

**Comment by MiahNelah** [comment] 2023-11-02 20:51
I pre-release version 0.7.3 with tposney's suggestion. Still testing it.

**Comment by MiahNelah** [comment] 2023-11-02 21:29
I tried many items, spells, class features and everything seems to work fine (awesome work btw, I need this so much in my games !). I release 0.7.3 already, please let me know if you still have issue.

**Comment by tposney** [comment] 2023-11-03 00:08
As mentioned it affects chris's premades a lot. The specific example I used for testing is sorcerers ability "Eldritch Invocations: Agonizing Blast" from Chri's premade items (which adds extra damage when casting eldritch blast), with libBlockly installed the extra damage is not added, with the change it is.

The problem seems to be that both modules use libwrapper to override Macro.execute and without the explicit return the macro.execute ends up not being awaitable, so midi proceeds before the macro execution completes (I think).

**Comment by tposney** [comment] 2023-11-03 00:16
I just updated and can confirm my test case now works as expected. Many thanks for the quick response.

**Comment by MiahNelah** [comment] 2023-11-03 07:54
I'm glad it works again ! I close this issue.

**Closed by MiahNelah** 2023-11-03 07:54 UTC
